import pyautogui
import time

time.sleep(2)
pyautogui.typewrite("Bababoi")
pyautogui.press('enter')
time.sleep(2)
pyautogui.typewrite("Add sheet Sheet1")
pyautogui.press('enter')
pyautogui.typewrite("Add column ['Roll_No',1, 2, 3, 4]")
pyautogui.press('enter')
pyautogui.typewrite("Add column ['Name','A', 'B', 'C', 'D']")
pyautogui.press('enter')
pyautogui.typewrite("Add column ['Bus_No', 23, 45, 53]")
pyautogui.press('enter')
pyautogui.typewrite("Add sheet Sheet2")
pyautogui.press('enter')
pyautogui.typewrite("Add column ['Roll_No',5, 6, 7, 8]")
pyautogui.press('enter')
pyautogui.typewrite("Add column ['Name','E', 'F', 'G', 'H']")
pyautogui.press('enter')
pyautogui.typewrite("Add column ['Marks', 27, 45, 59]")
pyautogui.press('enter')
time.sleep(1)
pyautogui.typewrite("Join Sheet1 Sheet2 Union Sheet3")
pyautogui.press('enter')
pyautogui.typewrite('plot color g')
pyautogui.press('enter')
pyautogui.typewrite("barh plot Name Marks")
pyautogui.press('enter')
