import pyautogui
import time

time.sleep(2)
pyautogui.typewrite("Bababoi")
pyautogui.press('enter')
pyautogui.typewrite("Add sheet Sheet1")
pyautogui.press('enter')
pyautogui.typewrite("Add column ['Roll_No',1, 2, 3, 4]")
pyautogui.press('enter')
pyautogui.typewrite("Add column ['Name','A', 'B', 'C', 'D']")
pyautogui.press('enter')
pyautogui.typewrite("Add column ['Bus_No', 23.3, 45.3, 53]")
pyautogui.press('enter')
pyautogui.typewrite("Add sheet Sheet2")
pyautogui.press('enter')
pyautogui.typewrite("Add column ['Roll_No',5, 6, 7, 8]")
pyautogui.press('enter')
pyautogui.typewrite("Add column ['Name','E', 'F', 'G', 'H']")
pyautogui.press('enter')
pyautogui.typewrite("Add column ['Marks', 27, 45, 59]")
pyautogui.press('enter')
pyautogui.typewrite('plot color green')
pyautogui.press('enter')
pyautogui.typewrite("Join Sheet1 Sheet2 Union Sheet3")
pyautogui.press('enter')
'''
pyautogui.typewrite('MaX Bus_No')
pyautogui.press('enter')
pyautogui.typewrite('Min Bus_No')
pyautogui.press('enter')
pyautogui.typewrite('Len Bus_No')
pyautogui.press('enter')
pyautogui.typewrite('Last Bus_No')
pyautogui.press('enter')
pyautogui.typewrite('First Bus_No')
pyautogui.press('enter')
pyautogui.typewrite("Hist plot Marks")
pyautogui.press('enter')
pyautogui.typewrite("BAr plot Name Marks")
pyautogui.press('enter')
pyautogui.typewrite("Barh plot Name Marks")
pyautogui.press('enter')
pyautogui.typewrite("Line plot Marks")
pyautogui.press('enter')
pyautogui.typewrite("Scatter plot Name Marks")
pyautogui.press('enter')
pyautogui.typewrite("Pie plot Name Marks")
pyautogui.press('enter')'''

